### ISSUE TITLE
[Windows] Image distorted

### ISSUE THREAD

**Issue by demilich1** [quadrupleslap/scrap#10] opened 2017-06-27 09:29 UTC
`cargo run --example screenshot`

produces a distorted image on my Windows 10 machine. There are no panics and the output is a valid .png, but somehow the pixels are not where they should be. Find an example attached to this issue:

![screenshot](https://user-images.githubusercontent.com/13793386/27580723-de58f2ca-5b2b-11e7-82dd-3fd053863949.png)

**Comment by quadrupleslap** [comment] 2017-06-27 20:45
Thanks for the report!

1. Any tips on how I can reproduce this error?
2. Can you also show what the image was *expected* to look like?

**Comment by demilich1** [comment] 2017-06-28 07:42
Well, reproducing it is just a matter of running the screenshot example on Windows 10. I did not add or change any code, just ran these two commands:
`git clone https://github.com/quadrupleslap/scrap.git`
and then
`cargo run --example screenshot`


This produces the screenshot.png in my first post. It is just a snapshot of my desktop, I attached the correct version down below:

![screenshot_correct](https://user-images.githubusercontent.com/13793386/27625762-ede77fee-5be5-11e7-9811-2a0ccca87c19.png)

**Comment by quadrupleslap** [comment] 2017-06-28 09:59
🤔 Well, it works fine for me on Windows 10, so that doesn't narrow things down. Sorry for bothering you, but:

- Are you using a high DPI display?
- Can you try replacing the "png" extension with a "bmp" one in `screenshot.rs` just to make sure it isn't a problem with `image`?

**Comment by demilich1** [comment] 2017-06-28 11:34
So it seems this is not a general WIndows 10 issue, but maybe somehow related to my specific configuration.

* I am using two rather old Samsung monitors with a native resolution of 1680x1050
* I just tried replacing .png with .bmp, the result is the same

I may be able to test this on another Windows 10 machine this evening, I will let you know if there is the same issue or if it works

**Comment by demilich1** [comment] 2017-06-29 09:05
I was able to test this on another Windows 10 machine... everything worked fine. So this is somehow related to my hardware/software setup. I updated my graphics driver (running a GeForce 460 GTX) and still get distorted screenshots. So I don't know what the problem is, but if no other users are affected it may be an isolated problem.

**Comment by quadrupleslap** [comment] 2017-06-29 10:35
Oh, the graphics card might be it! The library is dependent on Direct3D 11, which the card probably will, but might not, support. Not sure how that would result in this kind of glitching, though.

**Comment by demilich1** [comment] 2017-06-29 11:30
According to [Wikipedia](https://en.wikipedia.org/wiki/GeForce_400_series) Direct3D 11 should be supported for the GTX 460. But maybe this is still somehow a problem. Do you see any way to maybe downgrade that dependency to Direct3D 9? I mean, even a 20 year old graphics should be able to take screenshots, right?

**Comment by quadrupleslap** [comment] 2017-06-29 12:41
According to [Microsoft](https://msdn.microsoft.com/en-us/library/windows/desktop/hh404490(v=vs.85).aspx), Desktop Duplication requires DXGI 1.2, i.e. Direct3D 11.1, but according to the Wikipedia article it only supports Direct3D 11.0. Adding backwards compatibility will most likely require doing something like what [OBS Studio](https://github.com/jp9000/obs-studio/blob/master/plugins/win-capture/dc-capture.c) does as a fallback. The strangest thing is, why does it still produce a pretty similar image if it shouldn't support the API?

**Comment by demilich1** [comment] 2017-06-29 14:48
Yeah, that is a bit strange. Still, it is at least a semi-logical explanation for the behaviour ;) The other Windows machine I tested on had a GTX 1070 btw, so that would fit as well

**Comment by quadrupleslap** [comment] 2017-07-01 11:21
Okay, I'm closing this because it seems to be resolved, but I also opened #11. Also, do you think that a fallback for DirectX 9.0-11.0 is worth implementing?

**Closed as completed** 2017-07-01 11:22 UTC
Labels: bug

**Comment by demilich1** [comment] 2017-07-03 11:54
Well, of course I may be biased, but I do think it would be worth it. There are many computers with old hardware out there and at least I would expect screenshotting to work on basically any machine. Just my opinion though.

No matter if you decide to implement the fallback or not, I think this is a cool crate.. thank you for it!

**Comment by mallochine** [comment] 2017-11-20 01:18
I'd like the fallback. By the way, for some reason I saw distorted pic with DirectX 12.0

**Comment by quadrupleslap** [comment] 2018-01-04 09:49
Oh my god I'm an idiot - the stride was more than just the width! The problem's fixed now for the screenshot, but not for the ffplay example yet. I should also probably add a warning in the README.
