### ISSUE TITLE
Support DirectX 12

### ISSUE THREAD

**Issue by mallochine** [quadrupleslap/scrap#14] opened 2017-11-20 01:45 UTC
I ran the example "screenshot" and got a distorted image with DirectX 12.

By the way, if you can provide me with pointers on how to fix this bug for you, that'd be great. 'scrap' was the fastest screenshotting library for me.

**Comment by quadrupleslap** [comment] 2017-11-20 04:29
I'm installing qemu on my box right now! Sorry, I have no idea why this is happening - do you have any idea?

**Comment by mallochine** [comment] 2017-11-20 17:22
Mmm yeah...looks like scrap only supports DirectX 11 API.

**Comment by mallochine** [comment] 2017-11-20 18:10
This crate also used DirectX 11 API but I got a blank screen instead: https://github.com/bryal/dxgcap-rs/blob/master/src/lib.rs

**Comment by quadrupleslap** [comment] 2017-11-21 12:18
Oh, that's a surprise. If it's not too much trouble, can you try running https://code.msdn.microsoft.com/windowsdesktop/Desktop-Duplication-Sample-da4c696a and see if it works? Because if it does, I'll try following it as closely as possible, which should provide a working solution for DirectX 11 and 12.

**Comment by quadrupleslap** [comment] 2017-11-21 14:11
Okay, cannot reproduce with:
- QEMU
- Windows 10 Home (Version 1709, Build 16299.64)
- DirectX 12

Edit: Also cannot reproduce with the same drive but booted normally (with a GTX 1070.)

What system are you running on?

**Comment by mallochine** [comment] 2017-11-21 18:17
hm I'm using Intel(R) HD Graphics 4000. OS is Windows 10 Home 64-bit (10.0, Build 15063)

**Comment by mallochine** [comment] 2017-11-21 18:26
yeah I ran that C++ project and it appears to work.

It looks like mirrors just all the way down. Is this expected?

![image](https://user-images.githubusercontent.com/1282950/33089739-6bb1714a-cea6-11e7-86cb-248ac67b3fc5.png)

**Comment by quadrupleslap** [comment] 2017-11-21 18:37
Yeah, that's what it's meant to do. Do you want to rewrite the Windows code to follow that C++ project or should I? Following that example and later adding a GDI fallback is probably the way to go.

**Comment by mallochine** [comment] 2017-11-21 18:43
Yeah, to be fully reliable, need to use that C++ project and then always have GDI in case things fuck up.

**Comment by mallochine** [comment] 2017-11-21 18:43
I'll make a stab at it.

**Comment by quadrupleslap** [comment] 2017-11-21 18:47
Okay, good luck!

**Comment by mallochine** [comment] 2017-11-21 18:47
Hm wait, the existing code should be _rewritten_ to follow that Windows C++ code? Or just another case...?

**Comment by quadrupleslap** [comment] 2017-11-21 18:49
Rewritten, because both the existing code and the example are meant to use the Desktop Duplication API, which means the existing code is doing something wrong that the example is doing right.

**Comment by mallochine** [comment] 2017-11-21 22:24
you mean 'debugged' then....?

**Comment by quadrupleslap** [comment] 2017-11-22 03:21
I assumed a rewrite would be easier. :P

**Comment by quadrupleslap** [comment] 2017-11-23 10:06
Have you made any progress? If not, can I have a go at it?

**Comment by quadrupleslap** [comment] 2018-01-02 13:24
Double bump. =\

**Comment by mallochine** [comment] 2018-01-03 22:33
oh yeah go for it.

**Comment by mallochine** [comment] 2018-01-03 22:33
I decided to use a workaround.

**Comment by quadrupleslap** [comment] 2018-01-04 06:48
Could it just be that the PNG encoder is incorrectly assuming that `stride - width == 0`?

**Comment by quadrupleslap** [comment] 2018-01-04 12:10
Fixed in version `0.4.0`! 😄

**Closed as completed** 2018-01-04 12:11 UTC
Labels: bug

**Comment by mallochine** [comment] 2018-01-05 02:42
really. That simple.
